spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://revature.cr9qfziuu07o.us-west-2.rds.amazonaws.com:5432/postgres?currentSchema=clipr
spring.datasource.username=userTwo
spring.datasource.password=$p0ng3.b0b$$
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update